version: "3.8"

services:

  nginx:
    container_name: mk-burger-fast-proxy
    restart: 'no'
    build:
      context: nginx
    ports:
      - 80:80

  app:
    container_name: mk-burger-fast-api
    build:
      dockerfile: ./Dockerfile.prod
    image: mk-burger-fast-api:latest
    command: "gunicorn app.main:app --workers 2 --log-level info --access-logfile '-' --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    restart: 'no'
    environment:
      MK_BURGER_DATABASE_URL: postgresql+psycopg://mk_burger_fast_user:mk_burger_fast_password@database:5432/mk_burger_fast
    depends_on:
      - database

  database:
    container_name: mk-burger-fast-db
    build:
      context: postgres
    restart: 'no'
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=mk_burger_fast_password
      - POSTGRES_USER=mk_burger_fast_user
      - POSTGRES_DBS=mk_burger_fast, mk_burger_fast_test

volumes:
  pg_data:
