version: "3.8"

services:

  database:
    container_name: mk-burger-fast-db
    build:
      context: postgres
    restart: 'no'
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=mk_burger_fast_password
      - POSTGRES_USER=mk_burger_fast_user
      - POSTGRES_DBS=mk_burger_fast, mk_burger_fast_test
    ports:
      - 5434:5432

volumes:
  pg_data:
