"""Add created_at updated_at

Revision ID: 359a1f7d534f
Revises: 68838629b63f
Create Date: 2024-03-10 01:28:32.689592

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "359a1f7d534f"
down_revision: Union[str, None] = "68838629b63f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("breads", sa.Column("create_at", sa.DateTime(), nullable=True))
    op.add_column("breads", sa.Column("update_at", sa.DateTime(), nullable=True))
    op.add_column("burgers", sa.Column("create_at", sa.DateTime(), nullable=True))
    op.add_column("burgers", sa.Column("update_at", sa.DateTime(), nullable=True))
    op.add_column("meats", sa.Column("create_at", sa.DateTime(), nullable=True))
    op.add_column("meats", sa.Column("update_at", sa.DateTime(), nullable=True))
    op.add_column("optionals", sa.Column("create_at", sa.DateTime(), nullable=True))
    op.add_column("optionals", sa.Column("update_at", sa.DateTime(), nullable=True))
    op.add_column("status", sa.Column("create_at", sa.DateTime(), nullable=True))
    op.add_column("status", sa.Column("update_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("status", "update_at")
    op.drop_column("status", "create_at")
    op.drop_column("optionals", "update_at")
    op.drop_column("optionals", "create_at")
    op.drop_column("meats", "update_at")
    op.drop_column("meats", "create_at")
    op.drop_column("burgers", "update_at")
    op.drop_column("burgers", "create_at")
    op.drop_column("breads", "update_at")
    op.drop_column("breads", "create_at")
    # ### end Alembic commands ###
